# Site settings
title: Jonas Joehnk
email: jonasjoehnk94@gmail.com
url: https://jjoehnk.github.io
description: #"Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: "Jonas Joehnk's Portfolio"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
    #url: https://twitter.com/SBootstrap
  #- title: facebook
  #  url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  - title: linkedin
    url: https://www.linkedin.com/in/jonas-joehnk/
  - title: github
    url: https://github.com/jjoehnk

# Build settings
markdown: kramdown
permalink: pretty
